name: flask-restplus-production-skeleton
channels:
- conda-forge
- defaults
dependencies:
- ca-certificates=2018.1.18-0=0
- click=6.7=py36_0
- itsdangerous=0.24=py36_0
- jinja2=2.10=py36_0
- markupsafe=1.0=py36_0
- ncurses=5.9=10
- openssl=1.0.2l=0
- pip=9.0.3=py36_0
- python=3.6.2=0
- readline=6.2=2
- setuptools=27.2.0=py36_0
- sqlite=3.13.0=1
- tk=8.5.19=2
- werkzeug=0.12.2=py36_0
- wheel=0.31.0=py36_0
- xz=5.2.3=0
- zlib=1.2.11=0
- flask=0.12.2=py36_0
- pip:
  - gunicorn==19.7.1
  - flask-restplus==0.10.1
